#spring:
  #datasource:
   # hikari:
    #  username: root
     # password: kartik1202
      #jdbc-url: jdbc:mysql://localhost:3306/project
      #driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa:
   #   show-sql: true
    #  hibernate:
     #   ddl-auto: update
     # properties.hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
